### PR TITLE
PR: Remove spyder org CSS link

### LINKED ISSUE #31: Don't use spyder org CSS
Remove link to CSS used by the Spyder org website while ensuring that the visual keep the same

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #31

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Thanks! As you mention, we need to ensure that there are no regressions, since some styles from `style.css` do get applied.

In my informal testing so far, these include the font face, style, color, line height, etc, the heading padding, the link color, button properties, and styling for special elements like the Open Chat button and the pipe span. Chrome's coverage tool is super useful at finding these, as you're likely aware.

Let me know when you're ready for me to test this further!

**Review by CAM-Gerlach — APPROVED** [review]
I approve what I did and it won't let you since you're PR author, so go ahead and merge when you think its ready. Thanks @dalthviz !

**Review by dalthviz — COMMENTED** [review]
LGTM :+1: but probably having someone else reviewing it could be better

**Review by juanis2112 — APPROVED** [review]
Looks good to me. Thanks @dalthviz and @CAM-Gerlach!

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
