### PR TITLE
PR: Add Spyder style and update navbar and content margins

### PR DESCRIPTION
**Pull request by dalthviz**
A preview:

sdw

image

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, could you update the gif above with the latest changes?

**Comment by dalthviz** [comment]
@ccordoba12 could we merge this to continue with the footer in another PR or there is more things to change here?

**Comment by goanpeca** [comment]
@ccordoba12 I suggest we merge this as is (this is open for 3 months now).

**Comment by dalthviz** [comment]
Note: 
- [x] Change navbar buttons (don't make them totally red on click/hover)
- [x] Change back/forward arrows style
- [x] Remove social links (~~probably part of the config~~ part of the config - just don't add links for twitter/facebook)
- [x] Increase responsive navbar height

A preview:

theme

@ccordoba12 after this gets merged I will check the changes to support the navigation only in the side navbar and  if is worthy to rebase all of the work into an updated version of the original pandas repo

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot @dalthviz, I really like your last changes!

**Pull request merged**
