### PR TITLE
PR: Initial redo of contents titles handling in sidebar

### PR DESCRIPTION
**Pull request by dalthviz**
A preview:

theme

### CODE REVIEW

**Comment by ccordoba12** [comment]
This is looking really nice, great work @dalthviz!

**Comment by ccordoba12** [comment]
@dalthviz, this is looking awesome!! Thanks a lot for your work on this one!

From the last screenshots you posted above, I only have one minor comment to make, according to what we discussed with @juanis2112 in our last meeting. Please remember that we agreed to make the names of collapsible sections (such as `User Guide` and `Demo site`) all in capital letters.

**Comment by dalthviz** [comment]
@ccordoba12 I think this is ready

**Review by ccordoba12 — APPROVED** [review]
This is so nice!! I really like what you did to separate the buttons in the bottom bar when the screen is small.

Let's merge it so you can start the deployment now.

**Pull request merged**
