### PR TITLE
PR: Add new text and reST element styles

### LINKED ISSUE #24: New styles for different types of text in docs
@isabela-pf will help us decide on different styles for:
- Shortcuts
- Guilabels
- Links
- Text in monospaced font (code)
- Bold for emphasis

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Adds the styles specified in #24 to the site's theme.

Implements the styles exactly as described and decided therein. Screenshot showing all of them (normal, emphasis, link, code, kbd and guilabel, plus their variants) in a few different contexts:

(Image 0)

image

~One potential issue I noticed: the guilabel/menuselection style is pretty hard to tell apart, to my eye, to that used for keyboard shortcuts except for the slightly different color (that's very hard to see at that small size) and the monospaced font (which isn't obvious for keyboard shortcuts with only a few characters, i.e. most of them). Not a huge problem; it could be solved by trying @isabela-pf 's other alternative for guilabel colors, but that does draw more attention to them, perhaps too much. Here's how that looks:~ Fixed by making the background per-key, as originally intended, without actually adding/changing anything

(Image 1)

<details>

image

</details>

Similarly, the verbatim color looks almost identical, to my eye, to the link color, so similarly I have trouble distinguishing them when scanning the text, confusing me to what's a link and what's code. Using @isabela-pf 's other alternative color would solve that problem, but I can barely tell it apart from regular text, which is why we went with the first option:

(Image 2)

<details>

image

</details>

Keeping the color we agreed on and just adding the background color to verbatim blocks (as is common on most code sites, including `this one`) makes them look much more distinct, though it does reduce the contrast a little.

(Image 3)

<details>

image

</details>

@isabela-pf /others thoughts?

Resolve #24

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
A minor fix to the keyboard shortcut style, so that the background is applied to each key (as it was intended to be) rather than the whole monolithic shortcut, resolves most of the ambiguity between guilabels and keyboard shortcuts without having to change any of the styles, fonts or colors.

image

**Comment by isabela-pf** [comment]
Looks good to me! Thanks for testing all of these directions out and giving detailed explanations, it's really helpful for picking up this issue again now that it's in PR form. Nice catch making the shortcuts applied to each key! 

The idea behind the monospaced versus link colors was that links need a bright color more since they share the same font and such with the surrounding content and the color is the one thing distinguishing it. Monospaced have the different font to help distinguish them (and looks different enough from shortcuts since they lack the background) that they can afford to risk blending in with the dark color of the background, so that's why I preferred the darker option. Both options can work, though, so it's kind of up to what the team wants to prioritize: the brighter colors or it being easier to tell apart some of these styles.

**Comment by CAM-Gerlach** [comment]
Thanks for your thoughtful and detailed feedback, @isabela-pf ; I am glad that trying the different variations didn't go to waste.

While I was one of the strongest advocates of the brighter original color, I'm now convinced your preference for the darker color (and no background) was the right one. The code doesn't _need_ to stand out to a quick scan; in fact, that's rather counterproductive as its rather garish, distracting and draws undue attention to itself. On closer inspection, it does look distinct (due to a combination of the subtle color and the monospace font), which is where it matters (users telling what specific text is code and what is not), and I'm also averse to introducing a one-off bespoke color that doesn't really fit with the rest just for one specific element as opposed to one consistent with the rest that we can reuse for other things (IIRC we already used it for something in the new website theme), and it avoids looking too similar to the links.

Therefore, my recommendation to resolve the link-code confusion issue (as well as the others we've mentioned) would be _to go with the darker option you preferred for code_, as shown in Image 2 above. @juanis2112 @ccordoba12 @dalthviz thoughts?

**Comment by CAM-Gerlach** [comment]
> Therefore, my recommendation to resolve the link-code confusion issue (as well as the others we've mentioned) would be _to go with the darker option you preferred for code_, as shown in Image 2 above. @juanis2112 @ccordoba12 @dalthviz thoughts?

@ccordoba12 @juanis2112 @dalthviz ^ Ping...

**Comment by CAM-Gerlach** [comment]
After discussing it with @ccordoba12 and @juanis2112 , they still didn't like the dark red color, and after much debate suggested using the same BG and FG colors for code that the [VSCode docs](https://code.visualstudio.com/docs/cpp/cpp-debug), similar to Image 3 in the OP. On one hand, the lighter background color avoids the contrast issue mentioned with Image 3, and the change to how KB shortcuts are displayed per-key has reduced the similarity with that, so this makes the text more distinct from both links and its surroundings, though there is still some level of concern there. However, on the other hand its adding two new colors to the palette, which runs contrary to ensuring a more cohesive, coordinate style and to the work @isabela-pf has done on that.

@isabela-pf , thoughts? Maybe this could work with similar colors within the palette you've created?

image

**Comment by isabela-pf** [comment]
Sounds good to me! I think this works and can fit with colors already being used. It looks like we can still use the `#ededed` background and the brighter red (I believe it is still `#d50000`, but it's been a while so if it has changed my goal is to make it match). This keeps a unified palette but looks more like VS Codes choice.

**Review by juanis2112 — APPROVED** [review]
Thanks for implementing this. I think we can merge it for now

**Comment by CAM-Gerlach** [comment]
Okay, I implemented the proposal plus @isabela-pf 's tweak as suggested above to match our existing palette; our primary `#d50000` color looks essentially identical to the `#c7254e` color used by VSCode, and picked up our existing background color `#ededed` to sub in for the `#f9f2f4` used by VSCode.

EDIT: Forgot to actually paste the screenshot

image

This is essentially option 3 of the OP with a slightly tweaked text color, but my one concern with that though remains: as our background color is substantially darker than that used by VSCode (and a number of other docs I've seen that use the same or very similar ones), the contrast and readability of the text—perhaps the most critical on the page in terms of the user being able to read every letter easily and correctly—is reduced.

@isabela-pf , in light of that, do you suggest we

1. Keep the darker background color
2. Use the lighter VSCode background color 
3. Use a different, lighter background color from your palette or that would better match it?

**Review by ccordoba12 — APPROVED** [review]
Looks good to me too, thanks @CAM-Gerlach!

**Comment by ccordoba12** [comment]
@CAM-Gerlach, is there something missing here? Or is ready to be merged?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 As we discussed at the meeting, we're waiting on @isabela-pf 's reply to my comment directly above yours.

**Comment by isabela-pf** [comment]
Sorry for holding this up! Thanks for mentioning me to give another reminder.

I do think I prefer to keep one background color for ease of use and because it will look cleaner on the page (imagine a docs page with two slightly different grays throughout). If there's a concern about contrast, then I'd recommend changing the palette and switching out `#ededed`for `#f7f7f7` throughout the website. I think it should still work for all uses.

**Comment by CAM-Gerlach** [comment]
Okay, thanks much @isabela-pf . For now, let's just merge this as-is with `#ededed`, and if it becomes a concern, we can consider the change separately.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, this has a merge conflict now.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Yeah I was in the process of rebasing it, but my browser froze and eventually crashed before I could merge it.

**Comment by CAM-Gerlach** [comment]
I triggered a rebuild on Travis (it needed it anyway because linkcheck had a random failure; when we port to Github actions I won't run that on mainline branch builds), but its been sitting in the queue for the past hour.

**Pull request merged**
