### PR TITLE
PR: Initial responsive navbar for page outline

### PR DESCRIPTION
**Pull request by dalthviz**
A preview:

outline_r

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, please do the following changes:

1. Reduce the size of the hamburger button placed on the bottom so it looks clearly smaller than the one at the top.
2. Hide the "Edit this page" link when viewing the page on small screens and instead change it for the text "On this page". But leave that link for large screens.
3. Add a shadow or border on top of the navbar at the bottom so users can differentiate it from the rest of the text (there's already a border, I think, for the navbar at the top).
4. Leave one animated gif in the description: the one with the latest design, and remove the rest.

**Comment by ccordoba12** [comment]
Thanks @dalthviz, this is looking much better!

My new take:

* Please remove the icon to the left of "On this page" and just leave the text.
* Please remove the shadow you added on top and simply leave the same gray border of the navbar placed at the top.

**Comment by ccordoba12** [comment]
@dalthviz, could you update the gif above to appreciate your latest changes?

**Comment by ccordoba12** [comment]
Ok, this is looking terribly good! Last comment:

Could you reduce the padding of the top nav bar a bit? Perhaps 2 or 3px above and below?

The VSCode docs navbar looks slimmer and I'd like to see something like that here too:

Selección_038

Selección_037

**Comment by ccordoba12** [comment]
Great work @dalthviz! I'd say this is ready, but let's see what @goanpeca thinks about it.

**Comment by goanpeca** [comment]
Looks pretty cool! great work @dalthviz

**Review by goanpeca — APPROVED** [review]
Awesome :-)

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
