### PR TITLE
PR: Adjust the navbar and footer to more closely match that on the main site

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Per the discussion in spyder-ide/website-spyder#182 and the changes implemented in spyder-ide/lektor-icon#16 , fixes several outstanding issues with the docs navbar not matching that of the main website, as well as adds the external link styling agreed with @isabela-pf . It'll need a trivial doc-side PR to change the UI text and retrigger a build, similar to spyder-ide/lektor-icon#16  .

* [x] Make navbar height and width match that used from the beginning on main website theme
* [x] Make external links and footer match higher-contrast colors on main site, as discussed in spyder-ide/website-spyder#183 and implemented in spyder-ide/website-spyder#187 
* [x] Implement new current external link styling, with light bold and underline, following spyder-ide/lektor-icon#16
* [x] Update Node-SASS and SASS-Loader versions for compat with Node 15.x and NPM 7.x (should still be compatible with 14.x/6.x)

image

Its not a 100% perfect match at every smaller width (mobile, etc) since the two themes handle that differently, but it should get pretty close for now without the significant out of scope rework that harmonizing the latter would require.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @juanis2112 Changed to only add the red underline for the current link to the docs index page, and add separate classes for the link representing the current section vs. current actual page so its easy to style them separately in the future with theme or docs-side CSS, should we choose. Once this is approved and merged, I can go ahead with the docs PR that simply changes the text from Home -> Docs (to avoid multiple extra builds and rebase passes).

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @CAM-Gerlach!

**Review by juanis2112 — APPROVED** [review]
Thanks CAM!

**Comment by CAM-Gerlach** [comment]
@dalthviz , any last thoughts before merging this? It upgrades a couple of dependencies for compat with current Node/NPM versions, so want to make sure you're good with that.

**Comment by dalthviz** [comment]
@CAM-Gerlach just to be sure the static sources are being updated, right? Since @ccordoba12 and @juanis2112 already approved this could be merged (ideally by one of them)

**Comment by CAM-Gerlach** [comment]
@dalthviz With each commit I've updated the SCSS sources, run the webpack build with `npm` to update the generated/minified CSS and confirmed that the changes are reflected building the Spyder docs, if that's what you mean.

**Pull request merged**
